package lm;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Profile implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "USERPROFILE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "USERPROFILE_ID_SEQ", name = "USERPROFILE_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("UserId")
   private java.lang.String userId;

   @org.kie.api.definition.type.Label("goalId")
   private java.lang.String goalId;

   @org.kie.api.definition.type.Label("goal")
   private java.lang.String goal;

   @org.kie.api.definition.type.Label("NextAction")
   private java.lang.String nextAction;

   @org.kie.api.definition.type.Label("messageId")
   private java.lang.String messageId;

   @org.kie.api.definition.type.Label("NextQuestion")
   private java.lang.String nextQuestion;

   @org.kie.api.definition.type.Label("RecommendGoal")
   private java.lang.String recommendGoal;

   @org.kie.api.definition.type.Label("SignalGoal")
   private java.lang.String signalGoal;

   @org.kie.api.definition.type.Label("Options")
   @javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
   private java.util.List<java.lang.String> options;

   @org.kie.api.definition.type.Label("firstQuestion")
   private boolean firstQuestion;

   @org.kie.api.definition.type.Label("DebtAndIncomeRatio")
   private java.lang.Double debtAndIncomeRatio;

   @org.kie.api.definition.type.Label("previousQuestion")
   private java.lang.String previousQuestion;

   @org.kie.api.definition.type.Label("previousAnswer")
   private java.lang.String previousAnswer;

   @org.kie.api.definition.type.Label("balance")
   private java.lang.Double balance;

   @org.kie.api.definition.type.Label("loanType")
   private java.lang.String loanType;

   @org.kie.api.definition.type.Label("processInstanceId")
   private java.lang.Long processInstanceId;

   @org.kie.api.definition.type.Label("overDue")
   private java.lang.String overDue;

   @org.kie.api.definition.type.Label("tag")
   private java.lang.String tag;

   @javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label("insightsList")
   private java.util.List<java.lang.String> insightsList;

   @org.kie.api.definition.type.Label("collegeSavingsPlan")
   private boolean collegeSavingsPlan;

   @org.kie.api.definition.type.Label("debtAmount")
   private java.lang.Double debtAmount;

   @org.kie.api.definition.type.Label("mortgageNetIncomeRatio")
   private java.lang.Double mortgageNetIncomeRatio;

   @org.kie.api.definition.type.Label("flatTrend")
   private boolean flatTrend;

   @org.kie.api.definition.type.Label("ccDebtAndIncomeRatio")
   private java.lang.Double ccDebtAndIncomeRatio;

   @org.kie.api.definition.type.Label("retirementAccountExistance")
   private boolean retirementAccountExistance;

   @org.kie.api.definition.type.Label("occupationHazard")
   private boolean occupationHazard;

   @org.kie.api.definition.type.Label("ccDebtAmount")
   private java.lang.Double ccDebtAmount;

   @org.kie.api.definition.type.Label("quovoData")
   private boolean quovoData;

   @org.kie.api.definition.type.Label("accountCategory")
   private java.lang.String accountCategory;

   @org.kie.api.definition.type.Label("accountOwnerType")
   private java.lang.String accountOwnerType;

   @org.kie.api.definition.type.Label("accountType")
   private java.lang.String accountType;

   @org.kie.api.definition.type.Label("accountValue")
   private java.lang.Double accountValue;

   @org.kie.api.definition.type.Label("userValue")
   private java.lang.Double userValue;

   @org.kie.api.definition.type.Label("connectionValue")
   private java.lang.Double connectionValue;

   @org.kie.api.definition.type.Label("creditLimit")
   private java.lang.Double creditLimit;

   @org.kie.api.definition.type.Label("creditCardOverdue")
   private boolean creditCardOverdue;

   @org.kie.api.definition.type.Label("creditCardLastPayment")
   private java.lang.Double creditCardLastPayment;

   @org.kie.api.definition.type.Label("insuranceSurrenderValue")
   private java.lang.Double insuranceSurrenderValue;

   @org.kie.api.definition.type.Label("insuranceDeathBenefit")
   private java.lang.Double insuranceDeathBenefit;

   @org.kie.api.definition.type.Label("savingsExistance")
   private boolean savingsExistance;

   @org.kie.api.definition.type.Label("savingsAmount")
   private java.lang.Double savingsAmount;

   @org.kie.api.definition.type.Label("monthlyIncomeExistance")
   private boolean monthlyIncomeExistance;

   @org.kie.api.definition.type.Label("monthlyIncome")
   private java.lang.Double monthlyIncome;

   @org.kie.api.definition.type.Label("monthlyExpenses")
   private java.lang.Double monthlyExpenses;

   @org.kie.api.definition.type.Label("mortgageAmount")
   private java.lang.Double mortgageAmount;

   @org.kie.api.definition.type.Label("yoyTrend")
   private java.lang.String yoyTrend;

   @org.kie.api.definition.type.Label("incomeIncrease")
   private boolean incomeIncrease;

   @org.kie.api.definition.type.Label("educationSavingsExistance")
   private boolean educationSavingsExistance;

   @org.kie.api.definition.type.Label("employment")
   private boolean employment;

   @org.kie.api.definition.type.Label("savingsAccount")
   private boolean savingsAccount;

   @org.kie.api.definition.type.Label("savingsAccountValue")
   private java.lang.Double savingsAccountValue;

   @org.kie.api.definition.type.Label("healthInsurance")
   private boolean healthInsurance;

   @org.kie.api.definition.type.Label("homeOwnersInsurance")
   private boolean homeOwnersInsurance;

   @org.kie.api.definition.type.Label("lifeInsurance")
   private boolean lifeInsurance;

   @org.kie.api.definition.type.Label("mortgage")
   private boolean mortgage;

   @org.kie.api.definition.type.Label("rent")
   private boolean rent;

   @org.kie.api.definition.type.Label("account529")
   private boolean account529;

   @org.kie.api.definition.type.Label("needEmergencyFund")
   private boolean needEmergencyFund;

   @org.kie.api.definition.type.Label("dependants")
   private boolean dependants;

   @org.kie.api.definition.type.Label("dependantsUnder18")
   private boolean dependantsUnder18;

   @org.kie.api.definition.type.Label("attendedCollege")
   private boolean attendedCollege;

   @org.kie.api.definition.type.Label("nextQuestionId")
   private java.lang.String nextQuestionId;

   @org.kie.api.definition.type.Label("previousQuestionId")
   private java.lang.String previousQuestionId;

   @org.kie.api.definition.type.Label("previousMonthlyIncome")
   private java.lang.Double previousMonthlyIncome;

   @org.kie.api.definition.type.Label(value = "annualIncome")
   private java.lang.Double annualIncome;

   @org.kie.api.definition.type.Label(value = "grossMonthlyIncome")
   private java.lang.Double grossMonthlyIncome;

   public Profile()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getUserId()
   {
      return this.userId;
   }

   public void setUserId(java.lang.String userId)
   {
      this.userId = userId;
   }

   public java.lang.String getGoalId()
   {
      return this.goalId;
   }

   public void setGoalId(java.lang.String goalId)
   {
      this.goalId = goalId;
   }

   public java.lang.String getGoal()
   {
      return this.goal;
   }

   public void setGoal(java.lang.String goal)
   {
      this.goal = goal;
   }

   public java.lang.String getNextAction()
   {
      return this.nextAction;
   }

   public void setNextAction(java.lang.String nextAction)
   {
      this.nextAction = nextAction;
   }

   public java.lang.String getMessageId()
   {
      return this.messageId;
   }

   public void setMessageId(java.lang.String messageId)
   {
      this.messageId = messageId;
   }

   public java.lang.String getNextQuestion()
   {
      return this.nextQuestion;
   }

   public void setNextQuestion(java.lang.String nextQuestion)
   {
      this.nextQuestion = nextQuestion;
   }

   public java.lang.String getRecommendGoal()
   {
      return this.recommendGoal;
   }

   public void setRecommendGoal(java.lang.String recommendGoal)
   {
      this.recommendGoal = recommendGoal;
   }

   public java.lang.String getSignalGoal()
   {
      return this.signalGoal;
   }

   public void setSignalGoal(java.lang.String signalGoal)
   {
      this.signalGoal = signalGoal;
   }

   public java.util.List<java.lang.String> getOptions()
   {
      return this.options;
   }

   public void setOptions(java.util.List<java.lang.String> options)
   {
      this.options = options;
   }

   public boolean getFirstQuestion()
   {
      return this.firstQuestion;
   }

   public void setFirstQuestion(boolean firstQuestion)
   {
      this.firstQuestion = firstQuestion;
   }

   public java.lang.Double getDebtAndIncomeRatio()
   {
      return this.debtAndIncomeRatio;
   }

   public void setDebtAndIncomeRatio(java.lang.Double debtAndIncomeRatio)
   {
      this.debtAndIncomeRatio = debtAndIncomeRatio;
   }

   public java.lang.String getPreviousQuestion()
   {
      return this.previousQuestion;
   }

   public void setPreviousQuestion(java.lang.String previousQuestion)
   {
      this.previousQuestion = previousQuestion;
   }

   public java.lang.String getPreviousAnswer()
   {
      return this.previousAnswer;
   }

   public void setPreviousAnswer(java.lang.String previousAnswer)
   {
      this.previousAnswer = previousAnswer;
   }

   public java.lang.Double getBalance()
   {
      return this.balance;
   }

   public void setBalance(java.lang.Double balance)
   {
      this.balance = balance;
   }

   public java.lang.String getLoanType()
   {
      return this.loanType;
   }

   public void setLoanType(java.lang.String loanType)
   {
      this.loanType = loanType;
   }

   public java.lang.Long getProcessInstanceId()
   {
      return this.processInstanceId;
   }

   public void setProcessInstanceId(java.lang.Long processInstanceId)
   {
      this.processInstanceId = processInstanceId;
   }

   public java.lang.String getOverDue()
   {
      return this.overDue;
   }

   public void setOverDue(java.lang.String overDue)
   {
      this.overDue = overDue;
   }

   public java.lang.String getTag()
   {
      return this.tag;
   }

   public void setTag(java.lang.String tag)
   {
      this.tag = tag;
   }

   public java.util.List<java.lang.String> getInsightsList()
   {
      return this.insightsList;
   }

   public void setInsightsList(java.util.List<java.lang.String> insightsList)
   {
      this.insightsList = insightsList;
   }

   public boolean isCollegeSavingsPlan()
   {
      return this.collegeSavingsPlan;
   }

   public void setCollegeSavingsPlan(boolean collegeSavingsPlan)
   {
      this.collegeSavingsPlan = collegeSavingsPlan;
   }

   public java.lang.Double getDebtAmount()
   {
      return this.debtAmount;
   }

   public void setDebtAmount(java.lang.Double debtAmount)
   {
      this.debtAmount = debtAmount;
   }

   public java.lang.Double getMortgageNetIncomeRatio()
   {
      return this.mortgageNetIncomeRatio;
   }

   public void setMortgageNetIncomeRatio(java.lang.Double mortgageNetIncomeRatio)
   {
      this.mortgageNetIncomeRatio = mortgageNetIncomeRatio;
   }

   public boolean isFlatTrend()
   {
      return this.flatTrend;
   }

   public void setFlatTrend(boolean flatTrend)
   {
      this.flatTrend = flatTrend;
   }

   public java.lang.Double getCcDebtAndIncomeRatio()
   {
      return this.ccDebtAndIncomeRatio;
   }

   public void setCcDebtAndIncomeRatio(java.lang.Double ccDebtAndIncomeRatio)
   {
      this.ccDebtAndIncomeRatio = ccDebtAndIncomeRatio;
   }

   public boolean isRetirementAccountExistance()
   {
      return this.retirementAccountExistance;
   }

   public void setRetirementAccountExistance(boolean retirementAccountExistance)
   {
      this.retirementAccountExistance = retirementAccountExistance;
   }

   public boolean isOccupationHazard()
   {
      return this.occupationHazard;
   }

   public void setOccupationHazard(boolean occupationHazard)
   {
      this.occupationHazard = occupationHazard;
   }

   public java.lang.Double getCcDebtAmount()
   {
      return this.ccDebtAmount;
   }

   public void setCcDebtAmount(java.lang.Double ccDebtAmount)
   {
      this.ccDebtAmount = ccDebtAmount;
   }

   public boolean isQuovoData()
   {
      return this.quovoData;
   }

   public void setQuovoData(boolean quovoData)
   {
      this.quovoData = quovoData;
   }

   public java.lang.String getAccountCategory()
   {
      return this.accountCategory;
   }

   public void setAccountCategory(java.lang.String accountCategory)
   {
      this.accountCategory = accountCategory;
   }

   public java.lang.String getAccountOwnerType()
   {
      return this.accountOwnerType;
   }

   public void setAccountOwnerType(java.lang.String accountOwnerType)
   {
      this.accountOwnerType = accountOwnerType;
   }

   public java.lang.String getAccountType()
   {
      return this.accountType;
   }

   public void setAccountType(java.lang.String accountType)
   {
      this.accountType = accountType;
   }

   public java.lang.Double getAccountValue()
   {
      return this.accountValue;
   }

   public void setAccountValue(java.lang.Double accountValue)
   {
      this.accountValue = accountValue;
   }

   public java.lang.Double getUserValue()
   {
      return this.userValue;
   }

   public void setUserValue(java.lang.Double userValue)
   {
      this.userValue = userValue;
   }

   public java.lang.Double getConnectionValue()
   {
      return this.connectionValue;
   }

   public void setConnectionValue(java.lang.Double connectionValue)
   {
      this.connectionValue = connectionValue;
   }

   public java.lang.Double getCreditLimit()
   {
      return this.creditLimit;
   }

   public void setCreditLimit(java.lang.Double creditLimit)
   {
      this.creditLimit = creditLimit;
   }

   public boolean isCreditCardOverdue()
   {
      return this.creditCardOverdue;
   }

   public void setCreditCardOverdue(boolean creditCardOverdue)
   {
      this.creditCardOverdue = creditCardOverdue;
   }

   public java.lang.Double getCreditCardLastPayment()
   {
      return this.creditCardLastPayment;
   }

   public void setCreditCardLastPayment(java.lang.Double creditCardLastPayment)
   {
      this.creditCardLastPayment = creditCardLastPayment;
   }

   public java.lang.Double getInsuranceSurrenderValue()
   {
      return this.insuranceSurrenderValue;
   }

   public void setInsuranceSurrenderValue(java.lang.Double insuranceSurrenderValue)
   {
      this.insuranceSurrenderValue = insuranceSurrenderValue;
   }

   public java.lang.Double getInsuranceDeathBenefit()
   {
      return this.insuranceDeathBenefit;
   }

   public void setInsuranceDeathBenefit(java.lang.Double insuranceDeathBenefit)
   {
      this.insuranceDeathBenefit = insuranceDeathBenefit;
   }

   public boolean isSavingsExistance()
   {
      return this.savingsExistance;
   }

   public void setSavingsExistance(boolean savingsExistance)
   {
      this.savingsExistance = savingsExistance;
   }

   public java.lang.Double getSavingsAmount()
   {
      return this.savingsAmount;
   }

   public void setSavingsAmount(java.lang.Double savingsAmount)
   {
      this.savingsAmount = savingsAmount;
   }

   public boolean isMonthlyIncomeExistance()
   {
      return this.monthlyIncomeExistance;
   }

   public void setMonthlyIncomeExistance(boolean monthlyIncomeExistance)
   {
      this.monthlyIncomeExistance = monthlyIncomeExistance;
   }

   public java.lang.Double getMonthlyIncome()
   {
      return this.monthlyIncome;
   }

   public void setMonthlyIncome(java.lang.Double monthlyIncome)
   {
      this.monthlyIncome = monthlyIncome;
   }

   public java.lang.Double getMonthlyExpenses()
   {
      return this.monthlyExpenses;
   }

   public void setMonthlyExpenses(java.lang.Double monthlyExpenses)
   {
      this.monthlyExpenses = monthlyExpenses;
   }

   public java.lang.Double getMortgageAmount()
   {
      return this.mortgageAmount;
   }

   public void setMortgageAmount(java.lang.Double mortgageAmount)
   {
      this.mortgageAmount = mortgageAmount;
   }

   public java.lang.String getYoyTrend()
   {
      return this.yoyTrend;
   }

   public void setYoyTrend(java.lang.String yoyTrend)
   {
      this.yoyTrend = yoyTrend;
   }

   public boolean isIncomeIncrease()
   {
      return this.incomeIncrease;
   }

   public void setIncomeIncrease(boolean incomeIncrease)
   {
      this.incomeIncrease = incomeIncrease;
   }

   public boolean isEducationSavingsExistance()
   {
      return this.educationSavingsExistance;
   }

   public void setEducationSavingsExistance(boolean educationSavingsExistance)
   {
      this.educationSavingsExistance = educationSavingsExistance;
   }

   public boolean isEmployment()
   {
      return this.employment;
   }

   public void setEmployment(boolean employment)
   {
      this.employment = employment;
   }

   public boolean isSavingsAccount()
   {
      return this.savingsAccount;
   }

   public void setSavingsAccount(boolean savingsAccount)
   {
      this.savingsAccount = savingsAccount;
   }

   public java.lang.Double getSavingsAccountValue()
   {
      return this.savingsAccountValue;
   }

   public void setSavingsAccountValue(java.lang.Double savingsAccountValue)
   {
      this.savingsAccountValue = savingsAccountValue;
   }

   public boolean isHealthInsurance()
   {
      return this.healthInsurance;
   }

   public void setHealthInsurance(boolean healthInsurance)
   {
      this.healthInsurance = healthInsurance;
   }

   public boolean isHomeOwnersInsurance()
   {
      return this.homeOwnersInsurance;
   }

   public void setHomeOwnersInsurance(boolean homeOwnersInsurance)
   {
      this.homeOwnersInsurance = homeOwnersInsurance;
   }

   public boolean isLifeInsurance()
   {
      return this.lifeInsurance;
   }

   public void setLifeInsurance(boolean lifeInsurance)
   {
      this.lifeInsurance = lifeInsurance;
   }

   public boolean isMortgage()
   {
      return this.mortgage;
   }

   public void setMortgage(boolean mortgage)
   {
      this.mortgage = mortgage;
   }

   public boolean isRent()
   {
      return this.rent;
   }

   public void setRent(boolean rent)
   {
      this.rent = rent;
   }

   public boolean isAccount529()
   {
      return this.account529;
   }

   public void setAccount529(boolean account529)
   {
      this.account529 = account529;
   }

   public boolean isNeedEmergencyFund()
   {
      return this.needEmergencyFund;
   }

   public void setNeedEmergencyFund(boolean needEmergencyFund)
   {
      this.needEmergencyFund = needEmergencyFund;
   }

   public boolean isDependants()
   {
      return this.dependants;
   }

   public void setDependants(boolean dependants)
   {
      this.dependants = dependants;
   }

   public boolean isDependantsUnder18()
   {
      return this.dependantsUnder18;
   }

   public void setDependantsUnder18(boolean dependantsUnder18)
   {
      this.dependantsUnder18 = dependantsUnder18;
   }

   public boolean isAttendedCollege()
   {
      return this.attendedCollege;
   }

   public void setAttendedCollege(boolean attendedCollege)
   {
      this.attendedCollege = attendedCollege;
   }

   public java.lang.String getNextQuestionId()
   {
      return this.nextQuestionId;
   }

   public void setNextQuestionId(java.lang.String nextQuestionId)
   {
      this.nextQuestionId = nextQuestionId;
   }

   public java.lang.String getPreviousQuestionId()
   {
      return this.previousQuestionId;
   }

   public void setPreviousQuestionId(java.lang.String previousQuestionId)
   {
      this.previousQuestionId = previousQuestionId;
   }

   public java.lang.Double getPreviousMonthlyIncome()
   {
      return this.previousMonthlyIncome;
   }

   public void setPreviousMonthlyIncome(java.lang.Double previousMonthlyIncome)
   {
      this.previousMonthlyIncome = previousMonthlyIncome;
   }

   public java.lang.Double getAnnualIncome()
   {
      return this.annualIncome;
   }

   public void setAnnualIncome(java.lang.Double annualIncome)
   {
      this.annualIncome = annualIncome;
   }

   public java.lang.Double getGrossMonthlyIncome()
   {
      return this.grossMonthlyIncome;
   }

   public void setGrossMonthlyIncome(java.lang.Double grossMonthlyIncome)
   {
      this.grossMonthlyIncome = grossMonthlyIncome;
   }

   public Profile(java.lang.Long id, java.lang.String name,
         java.lang.String userId, java.lang.String goalId,
         java.lang.String goal, java.lang.String nextAction,
         java.lang.String messageId, java.lang.String nextQuestion,
         java.lang.String recommendGoal, java.lang.String signalGoal,
         java.util.List<java.lang.String> options, boolean firstQuestion,
         java.lang.Double debtAndIncomeRatio, java.lang.String previousQuestion,
         java.lang.String previousAnswer, java.lang.Double balance,
         java.lang.String loanType, java.lang.Long processInstanceId,
         java.lang.String overDue, java.lang.String tag,
         java.util.List<java.lang.String> insightsList,
         boolean collegeSavingsPlan, java.lang.Double debtAmount,
         java.lang.Double mortgageNetIncomeRatio, boolean flatTrend,
         java.lang.Double ccDebtAndIncomeRatio,
         boolean retirementAccountExistance, boolean occupationHazard,
         java.lang.Double ccDebtAmount, boolean quovoData,
         java.lang.String accountCategory, java.lang.String accountOwnerType,
         java.lang.String accountType, java.lang.Double accountValue,
         java.lang.Double userValue, java.lang.Double connectionValue,
         java.lang.Double creditLimit, boolean creditCardOverdue,
         java.lang.Double creditCardLastPayment,
         java.lang.Double insuranceSurrenderValue,
         java.lang.Double insuranceDeathBenefit, boolean savingsExistance,
         java.lang.Double savingsAmount, boolean monthlyIncomeExistance,
         java.lang.Double monthlyIncome, java.lang.Double monthlyExpenses,
         java.lang.Double mortgageAmount, java.lang.String yoyTrend,
         boolean incomeIncrease, boolean educationSavingsExistance,
         boolean employment, boolean savingsAccount,
         java.lang.Double savingsAccountValue, boolean healthInsurance,
         boolean homeOwnersInsurance, boolean lifeInsurance, boolean mortgage,
         boolean rent, boolean account529, boolean needEmergencyFund,
         boolean dependants, boolean dependantsUnder18, boolean attendedCollege,
         java.lang.String nextQuestionId, java.lang.String previousQuestionId,
         java.lang.Double previousMonthlyIncome, java.lang.Double annualIncome,
         java.lang.Double grossMonthlyIncome)
   {
      this.id = id;
      this.name = name;
      this.userId = userId;
      this.goalId = goalId;
      this.goal = goal;
      this.nextAction = nextAction;
      this.messageId = messageId;
      this.nextQuestion = nextQuestion;
      this.recommendGoal = recommendGoal;
      this.signalGoal = signalGoal;
      this.options = options;
      this.firstQuestion = firstQuestion;
      this.debtAndIncomeRatio = debtAndIncomeRatio;
      this.previousQuestion = previousQuestion;
      this.previousAnswer = previousAnswer;
      this.balance = balance;
      this.loanType = loanType;
      this.processInstanceId = processInstanceId;
      this.overDue = overDue;
      this.tag = tag;
      this.insightsList = insightsList;
      this.collegeSavingsPlan = collegeSavingsPlan;
      this.debtAmount = debtAmount;
      this.mortgageNetIncomeRatio = mortgageNetIncomeRatio;
      this.flatTrend = flatTrend;
      this.ccDebtAndIncomeRatio = ccDebtAndIncomeRatio;
      this.retirementAccountExistance = retirementAccountExistance;
      this.occupationHazard = occupationHazard;
      this.ccDebtAmount = ccDebtAmount;
      this.quovoData = quovoData;
      this.accountCategory = accountCategory;
      this.accountOwnerType = accountOwnerType;
      this.accountType = accountType;
      this.accountValue = accountValue;
      this.userValue = userValue;
      this.connectionValue = connectionValue;
      this.creditLimit = creditLimit;
      this.creditCardOverdue = creditCardOverdue;
      this.creditCardLastPayment = creditCardLastPayment;
      this.insuranceSurrenderValue = insuranceSurrenderValue;
      this.insuranceDeathBenefit = insuranceDeathBenefit;
      this.savingsExistance = savingsExistance;
      this.savingsAmount = savingsAmount;
      this.monthlyIncomeExistance = monthlyIncomeExistance;
      this.monthlyIncome = monthlyIncome;
      this.monthlyExpenses = monthlyExpenses;
      this.mortgageAmount = mortgageAmount;
      this.yoyTrend = yoyTrend;
      this.incomeIncrease = incomeIncrease;
      this.educationSavingsExistance = educationSavingsExistance;
      this.employment = employment;
      this.savingsAccount = savingsAccount;
      this.savingsAccountValue = savingsAccountValue;
      this.healthInsurance = healthInsurance;
      this.homeOwnersInsurance = homeOwnersInsurance;
      this.lifeInsurance = lifeInsurance;
      this.mortgage = mortgage;
      this.rent = rent;
      this.account529 = account529;
      this.needEmergencyFund = needEmergencyFund;
      this.dependants = dependants;
      this.dependantsUnder18 = dependantsUnder18;
      this.attendedCollege = attendedCollege;
      this.nextQuestionId = nextQuestionId;
      this.previousQuestionId = previousQuestionId;
      this.previousMonthlyIncome = previousMonthlyIncome;
      this.annualIncome = annualIncome;
      this.grossMonthlyIncome = grossMonthlyIncome;
   }

}