package lm;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class UserProfile implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "USERPROFILE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "USERPROFILE_ID_SEQ", name = "USERPROFILE_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("UserId")
   private java.lang.String userId;

   @org.kie.api.definition.type.Label("GoalId")
   private java.lang.String goalId;

   @org.kie.api.definition.type.Label("Goal")
   private java.lang.String goal;

   @org.kie.api.definition.type.Label("PreviousQuestion")
   private java.lang.String previousQuestion;

   @org.kie.api.definition.type.Label("Answer")
   private java.lang.String answer;

   @org.kie.api.definition.type.Label("NextAction")
   private java.lang.String nextAction;

   @org.kie.api.definition.type.Label("MessageId")
   private java.lang.String messageId;

   @org.kie.api.definition.type.Label("NextQuestion")
   private java.lang.String nextQuestion;

   @org.kie.api.definition.type.Label("RecommendGoal")
   private java.lang.String recommendGoal;

   @org.kie.api.definition.type.Label("SignalGoal")
   private java.lang.String signalGoal;

   @org.kie.api.definition.type.Label("Balance")
   private java.lang.Double balance;

   @org.kie.api.definition.type.Label("LoanType")
   private java.lang.String loanType;

   @org.kie.api.definition.type.Label("Options")
   @javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
   private java.util.List<java.lang.String> options;

   @org.kie.api.definition.type.Label("firstQuestion")
   private boolean firstQuestion;

   @org.kie.api.definition.type.Label("ProcessInstanceId")
   private Long processInstanceId;

   @org.kie.api.definition.type.Label("OverDue")
   private java.lang.String overDue;

   @org.kie.api.definition.type.Label("Tag")
   private java.lang.String tag;

   @javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label("InsightsList")
   private java.util.List<java.lang.String> insightsList;

   @org.kie.api.definition.type.Label("SavingExistance")
   private java.lang.String savingExistance;

   @org.kie.api.definition.type.Label("SavingEstimate")
   private java.lang.Double savingEstimate;

   @org.kie.api.definition.type.Label("CollegeSavingsPlan")
   private boolean collegeSavingsPlan;

   @org.kie.api.definition.type.Label("Income")
   private java.lang.Double income;

   @org.kie.api.definition.type.Label("DebitEstimate")
   private java.lang.Double debitEstimate;

   @org.kie.api.definition.type.Label("MortgageNetIncomeRatio")
   private java.lang.Double mortgageNetIncomeRatio;

   @org.kie.api.definition.type.Label("YoyTrend")
   private boolean yoyTrend;

   @org.kie.api.definition.type.Label("DebtAndIncomeRatio")
   private java.lang.Double debtAndIncomeRatio;

   @org.kie.api.definition.type.Label("OccupationHazard")
   private boolean occupationHazard;

   @org.kie.api.definition.type.Label("FlatTrend")
   private boolean flatTrend;

   @org.kie.api.definition.type.Label(value = "QuovoData")
   private boolean quovoData;

   public UserProfile()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getUserId()
   {
      return this.userId;
   }

   public void setUserId(java.lang.String userId)
   {
      this.userId = userId;
   }

   public java.lang.String getGoalId()
   {
      return this.goalId;
   }

   public void setGoalId(java.lang.String goalId)
   {
      this.goalId = goalId;
   }

   public java.lang.String getGoal()
   {
      return this.goal;
   }

   public void setGoal(java.lang.String goal)
   {
      this.goal = goal;
   }

   public java.lang.String getPreviousQuestion()
   {
      return this.previousQuestion;
   }

   public void setPreviousQuestion(java.lang.String previousQuestion)
   {
      this.previousQuestion = previousQuestion;
   }

   public java.lang.String getAnswer()
   {
      return this.answer;
   }

   public void setAnswer(java.lang.String answer)
   {
      this.answer = answer;
   }

   public java.lang.String getNextAction()
   {
      return this.nextAction;
   }

   public void setNextAction(java.lang.String nextAction)
   {
      this.nextAction = nextAction;
   }

   public java.lang.String getMessageId()
   {
      return this.messageId;
   }

   public void setMessageId(java.lang.String messageId)
   {
      this.messageId = messageId;
   }

   public java.lang.String getNextQuestion()
   {
      return this.nextQuestion;
   }

   public void setNextQuestion(java.lang.String nextQuestion)
   {
      this.nextQuestion = nextQuestion;
   }

   public java.lang.String getRecommendGoal()
   {
      return this.recommendGoal;
   }

   public void setRecommendGoal(java.lang.String recommendGoal)
   {
      this.recommendGoal = recommendGoal;
   }

   public java.lang.String getSignalGoal()
   {
      return this.signalGoal;
   }

   public void setSignalGoal(java.lang.String signalGoal)
   {
      this.signalGoal = signalGoal;
   }

   public java.lang.Double getBalance()
   {
      return this.balance;
   }

   public void setBalance(java.lang.Double balance)
   {
      this.balance = balance;
   }

   public java.lang.String getLoanType()
   {
      return this.loanType;
   }

   public void setLoanType(java.lang.String loanType)
   {
      this.loanType = loanType;
   }

   public java.util.List<java.lang.String> getOptions()
   {
      return this.options;
   }

   public void setOptions(java.util.List<java.lang.String> options)
   {
      this.options = options;
   }

   public boolean getFirstQuestion()
   {
      return this.firstQuestion;
   }

   public void setFirstQuestion(boolean firstQuestion)
   {
      this.firstQuestion = firstQuestion;
   }

   public java.lang.Long getProcessInstanceId()
   {
      return this.processInstanceId;
   }

   public void setProcessInstanceId(java.lang.Long processInstanceId)
   {
      this.processInstanceId = processInstanceId;
   }

   public java.lang.String getOverDue()
   {
      return this.overDue;
   }

   public void setOverDue(java.lang.String overDue)
   {
      this.overDue = overDue;
   }

   public java.lang.String getTag()
   {
      return this.tag;
   }

   public void setTag(java.lang.String tag)
   {
      this.tag = tag;
   }

   public java.util.List<java.lang.String> getInsightsList()
   {
      return this.insightsList;
   }

   public void setInsightsList(java.util.List<java.lang.String> insightsList)
   {
      this.insightsList = insightsList;
   }

   public java.lang.String getSavingExistance()
   {
      return this.savingExistance;
   }

   public void setSavingExistance(java.lang.String savingExistance)
   {
      this.savingExistance = savingExistance;
   }

   public java.lang.Double getSavingEstimate()
   {
      return this.savingEstimate;
   }

   public void setSavingEstimate(java.lang.Double savingEstimate)
   {
      this.savingEstimate = savingEstimate;
   }

   public boolean isCollegeSavingsPlan()
   {
      return this.collegeSavingsPlan;
   }

   public void setCollegeSavingsPlan(boolean collegeSavingsPlan)
   {
      this.collegeSavingsPlan = collegeSavingsPlan;
   }

   public java.lang.Double getIncome()
   {
      return this.income;
   }

   public void setIncome(java.lang.Double income)
   {
      this.income = income;
   }

   public java.lang.Double getDebitEstimate()
   {
      return this.debitEstimate;
   }

   public void setDebitEstimate(java.lang.Double debitEstimate)
   {
      this.debitEstimate = debitEstimate;
   }

   public java.lang.Double getMortgageNetIncomeRatio()
   {
      return this.mortgageNetIncomeRatio;
   }

   public void setMortgageNetIncomeRatio(java.lang.Double mortgageNetIncomeRatio)
   {
      this.mortgageNetIncomeRatio = mortgageNetIncomeRatio;
   }

   public boolean isYoyTrend()
   {
      return this.yoyTrend;
   }

   public void setYoyTrend(boolean yoyTrend)
   {
      this.yoyTrend = yoyTrend;
   }

   public java.lang.Double getDebtAndIncomeRatio()
   {
      return this.debtAndIncomeRatio;
   }

   public void setDebtAndIncomeRatio(java.lang.Double debtAndIncomeRatio)
   {
      this.debtAndIncomeRatio = debtAndIncomeRatio;
   }

   public boolean isOccupationHazard()
   {
      return this.occupationHazard;
   }

   public void setOccupationHazard(boolean occupationHazard)
   {
      this.occupationHazard = occupationHazard;
   }

   public boolean isFlatTrend()
   {
      return this.flatTrend;
   }

   public void setFlatTrend(boolean flatTrend)
   {
      this.flatTrend = flatTrend;
   }

   public boolean isQuovoData()
   {
      return this.quovoData;
   }

   public void setQuovoData(boolean quovoData)
   {
      this.quovoData = quovoData;
   }

   public UserProfile(java.lang.Long id, java.lang.String name,
         java.lang.String userId, java.lang.String goalId,
         java.lang.String goal, java.lang.String previousQuestion,
         java.lang.String answer, java.lang.String nextAction,
         java.lang.String messageId, java.lang.String nextQuestion,
         java.lang.String recommendGoal, java.lang.String signalGoal,
         java.lang.Double balance, java.lang.String loanType,
         java.util.List<java.lang.String> options, boolean firstQuestion,
         java.lang.Long processInstanceId, java.lang.String overDue,
         java.lang.String tag, java.util.List<java.lang.String> insightsList,
         java.lang.String savingExistance, java.lang.Double savingEstimate,
         boolean collegeSavingsPlan, java.lang.Double income,
         java.lang.Double debitEstimate,
         java.lang.Double mortgageNetIncomeRatio, boolean yoyTrend,
         java.lang.Double debtAndIncomeRatio, boolean occupationHazard,
         boolean flatTrend, boolean quovoData)
   {
      this.id = id;
      this.name = name;
      this.userId = userId;
      this.goalId = goalId;
      this.goal = goal;
      this.previousQuestion = previousQuestion;
      this.answer = answer;
      this.nextAction = nextAction;
      this.messageId = messageId;
      this.nextQuestion = nextQuestion;
      this.recommendGoal = recommendGoal;
      this.signalGoal = signalGoal;
      this.balance = balance;
      this.loanType = loanType;
      this.options = options;
      this.firstQuestion = firstQuestion;
      this.processInstanceId = processInstanceId;
      this.overDue = overDue;
      this.tag = tag;
      this.insightsList = insightsList;
      this.savingExistance = savingExistance;
      this.savingEstimate = savingEstimate;
      this.collegeSavingsPlan = collegeSavingsPlan;
      this.income = income;
      this.debitEstimate = debitEstimate;
      this.mortgageNetIncomeRatio = mortgageNetIncomeRatio;
      this.yoyTrend = yoyTrend;
      this.debtAndIncomeRatio = debtAndIncomeRatio;
      this.occupationHazard = occupationHazard;
      this.flatTrend = flatTrend;
      this.quovoData = quovoData;
   }

}